"""Regression tests that lock the documented heating-circuit addresses in
``docs/Modbus-Register.md`` to the authoritative register map built by
``idm_heatpump.registers.build_register_map``.

The documented register table has drifted from the code in the past (the
0.6.0 release shifted six heating-circuit UCHAR blocks by +1 to eliminate a
documented logical range overlap; the code was later reverted to preserve the
overlap per AGENTS.md, but the docs were not updated). These tests parse the
markdown tables and fail on any future drift.
"""

from __future__ import annotations

import re
from pathlib import Path

from idm_heatpump.registers import IdmModelInfo, build_register_map

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs" / "Modbus-Register.md"

CIRCUITS = ["a", "b", "c", "d", "e", "f", "g"]

# Blocks that were affected by the historical 0.6.0 +1 drift. Each entry maps
# the documented register-name suffix (without the ``hc_X_`` prefix) to the
# code expression that produces its address. The test rebuilds the full map
# (all 7 circuits) and checks every documented address against it.
_HC_BLOCKS: dict[str, tuple[int, int]] = {
    # name suffix: (base address for circuit A, step per circuit index)
    "flow_temp": (1350, 2),
    "room_temp": (1364, 2),
    "setpoint_flow_temp": (1378, 2),
    "mode": (1393, 1),
    "room_setpoint_heat_normal": (1401, 2),
    "room_setpoint_heat_eco": (1415, 2),
    "heating_curve": (1429, 2),
    "heating_limit": (1442, 1),
    "setpoint_flow_constant": (1449, 1),
    "room_setpoint_cool_normal": (1457, 2),
    "room_setpoint_cool_eco": (1471, 2),
    "cooling_limit": (1484, 1),
    "setpoint_flow_cooling": (1491, 1),
    "active_mode": (1498, 1),
    "parallel_shift": (1505, 1),
    "ext_room_temp": (1650, 2),
}


def _build_full_map() -> dict[str, object]:
    model_info = IdmModelInfo(
        model_name="Navigator 10",
        active_heating_circuits=["A", "B", "C", "D", "E", "F", "G"],
        zone_modules=0,
        has_solar=True,
        has_isc=True,
        has_pv=True,
        has_cascade=True,
        features=set(),
        firmware_version=None,
    )
    return build_register_map(model_info)


def test_docs_file_exists() -> None:
    assert DOCS.is_file(), f"expected {DOCS} to exist"


def test_detailed_heating_circuit_table_matches_code() -> None:
    """Every ``hc_<circuit>_<suffix>`` row in the detailed table must match the
    address generated by the register map for that name."""
    text = DOCS.read_text(encoding="utf-8")
    full_map = _build_full_map()

    # Detailed table rows look like:
    #   | 1442 | `hc_a_heating_limit` | UCHAR | RW | °C | 0..50 | EEPROM |
    row_re = re.compile(r"^\|\s*(\d+)\s*\|\s*`hc_([a-g])_(\w+)`\s*\|", re.MULTILINE)
    matches = row_re.findall(text)
    assert matches, "expected to find detailed hc_* rows in the docs"

    failures: list[str] = []
    for documented_addr_str, circuit, suffix in matches:
        name = f"hc_{circuit}_{suffix}"
        documented_addr = int(documented_addr_str)
        reg = full_map.get(name)
        if reg is None:  # pragma: no cover - guards against typos in docs
            failures.append(f"{name}: not present in built register map")
            continue
        code_addr = int(getattr(reg, "address"))
        if code_addr != documented_addr:
            failures.append(f"{name}: docs say {documented_addr}, code says {code_addr}")

    assert not failures, "heating-circuit doc/code address drift:\n  " + "\n  ".join(
        sorted(failures)
    )


def test_patterns_table_base_addresses_match_code() -> None:
    """The ``## Heating Circuits A-G`` patterns table must list base addresses
    and steps that reproduce the addresses generated by the code."""
    text = DOCS.read_text(encoding="utf-8")

    # Restrict to the patterns table section so we do not pick up the detailed
    # table rows (which have a different column layout).
    section = text.split("## Heating Circuits A", 1)[-1]
    # Stop at the next top-level section.
    if "\n## " in section:
        section = section.split("\n## ", 1)[0]

    # Pattern rows look like:
    #   | 1442 | 1 | `hc_X_heating_limit` | UCHAR | RW | °C | 0..50 |
    row_re = re.compile(r"^\|\s*(\d+)\s*\|\s*(\d+)\s*\|\s*`hc_X_(\w+)`\s*\|", re.MULTILINE)
    matches = row_re.findall(section)
    assert matches, "expected to find hc_X_* pattern rows in the patterns table"

    failures: list[str] = []
    for base_str, step_str, suffix in matches:
        if suffix not in _HC_BLOCKS:
            continue
        documented_base, documented_step = int(base_str), int(step_str)
        code_base, code_step = _HC_BLOCKS[suffix]
        if documented_base != code_base:
            failures.append(f"hc_X_{suffix}: docs base {documented_base}, code base {code_base}")
        if documented_step != code_step:
            failures.append(f"hc_X_{suffix}: docs step {documented_step}, code step {code_step}")

    assert not failures, "patterns table base/step drift:\n  " + "\n  ".join(sorted(failures))
